@startuml
skinparam sequenceMessageAlign center
"Content Creator" --> "Content Consumer" : Send Concordance Report [LAB-90]
"Content Consumer" --> "Content Creator" : Send Concordance Report Response [LAB-90]
@enduml