@startuml
participant Content Data Structure Consumer
participant Content Creator
participant Content Consumer
participant Content Data Structure Creator

Content Data Structure Creator<-Content Data Structure Consumer:Retrieve Concordance Report Definition [LAB-91]
Content Data Structure Creator->Content Data Structure Consumer:Retrieve Concordance Report Definition Response [LAB-91]
Content Creator->Content Consumer:Send Concordance Report [LAB-90]
Content Consumer->Content Creator: Send Concordance Report Response [LAB-90]
@enduml