Instance: ScreeningImmunocompromisedLibrary
InstanceOf: Library
Title: "Immunocompromised Screening Library"
Usage: #example
* url = "http://OUR-PLACEHOLDER-URL.com/Library/RadPathGleasonCorrelation"
* name = "RadPathGleasonCorrelation"
* title = "Rad Path Gleason Correlation"
* type = #logic-library "Logic Library"
* status = http://hl7.org/fhir/publication-status#draft "Draft"
* description = "Rad Path Gleason Correlation"
* content[+].contentType = urn:ietf:bcp:13#text/cql "text/cql"
* content[=].data = "bGlicmFyeSBSYWRQYXRoUHJvc3RhdGUKCnVzaW5nIEZISVIgdmVyc2lvbiAnNC4wLjEnCgppbmNsdWRlIEZISVJIZWxwZXJzIHZlcnNpb24gJzQuMC4xJwppbmNsdWRlIEZISVJDb21tb24gY2FsbGVkIEZDCmluY2x1ZGUgUmFkUGF0aENvbW1vbiBjYWxsZWQgUlBDY29tCgpjb2Rlc3lzdGVtICJTTk9NRUQiOiAnaHR0cDovL3Nub21lZC5pbmZvL3NjdCcKY29kZXN5c3RlbSAiUkFETEVYIjogICdodHRwOi8vcmFkbGV4Lm9yZycKY29kZXN5c3RlbSAiQ0FQIjogJ2h0dHA6Ly9jYXAub3JnL2VDQycgCgovL0dsZWFzb24gU2NvcmUgY29kZXMKY29kZSAiR2xlYXNvbiBTY29yZSI6ICczNzIyNzgwMDAnIGZyb20gU05PTUVECmNvZGUgIlN0cnVjdHVyZSBvZiBwb3N0ZXJpb3Igc3VyZmFjZSBvZiBwcm9zdGF0ZSI6ICc1MDI2MDAzJyBmcm9tIFNOT01FRApjb2RlICJjbGluaWNhbGx5IHNpZ25pZmljYW50IHByb3N0YXRlIGNhbmNlciI6ICdSSUQ0OTUwMicgZnJvbSBSQURMRVgKY29kZSAiU2NvcmUgNyI6ICdDQVAjMTY4MTEnIGZyb20gQ0FQCgpjb250ZXh0IFBhdGllbnQKCmRlZmluZSAiR2xlYXNvbiBTY29yZSBBdmFpbGFibGUiOiAKICAgIFtPYnNlcnZhdGlvbl0gTwogICAgd2hlcmUgTy5jb2RlIH4gIkdsZWFzb24gU2NvcmUiCgpkZWZpbmUgIlJhZHMgY2xpbmljYWxseSBzaWduaWZpY2FudCBwcm9zdGF0ZSBjYW5jZXIiOiAKICAgICJHbGVhc29uIFNjb3JlIEF2YWlsYWJsZSIgTwogICAgICAgIHdoZXJlIChleGlzdHMgTy5jYXRlZ29yeSBDIHdoZXJlIEMgfiBSUENjb20uIkltYWdpbmciKQogICAgICAgIGFuZCAoTy52YWx1ZSBhcyBDb2RlYWJsZUNvbmNlcHQpIH4gImNsaW5pY2FsbHkgc2lnbmlmaWNhbnQgcHJvc3RhdGUgY2FuY2VyIgoKZGVmaW5lICJQYXRoIFNjb3JlIG9mIDciOiAKICAgICJHbGVhc29uIFNjb3JlIEF2YWlsYWJsZSIgTwogICAgICAgIHdoZXJlIChleGlzdHMgTy5jYXRlZ29yeSBDIHdoZXJlIEMgfiBSUENjb20uIkxhYm9yYXRvcnkiKQogICAgICAgIGFuZCAoTy52YWx1ZSBhcyBDb2RlYWJsZUNvbmNlcHQpIH4gIlNjb3JlIDci"